# Generated by Django 4.2.7 on 2023-12-21 12:56

import bboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999999999, max_length=8, validators=[bboard.models.validate_positive, django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
    ]
