# Generated by Django 4.2.7 on 2024-03-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_remove_bb__content_rendered_alter_bb_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='picture',
<<<<<<< HEAD
            field=models.ImageField(blank=True, null=True, upload_to='bb/%Y/%m/%d/', verbose_name='Изображение'),
=======
            field=models.ImageField(blank=True, null=True, upload_to='bb/%Y/%m/%d', verbose_name='Изображение'),
>>>>>>> a1c91d26af02f7a164213b1a68da31456ba370e2
        ),
    ]
