# Generated by Django 4.2.7 on 2024-03-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=100, verbose_name='Вкус')),
                ('topping', models.CharField(max_length=100)),
                ('is_vegan', models.BooleanField(default=False)),
            ],
        ),
    ]
