# Generated by Django 4.2.7 on 2024-03-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_img_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PGSProject',
        ),
        migrations.DeleteModel(
            name='PGSProject2',
        ),
        migrations.DeleteModel(
            name='PGSProject3',
        ),
        migrations.DeleteModel(
            name='PGSRoomReserving',
        ),
        migrations.DeleteModel(
            name='PGSRubric',
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
