# Generated by Django 4.2.7 on 2024-03-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_img_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_directory/', verbose_name='Файл PDF'),
        ),
        migrations.AddField(
            model_name='img',
            name='xlsx_file',
            field=models.FileField(blank=True, null=True, upload_to='xlsx_directory/', verbose_name='Файл XLSX'),
        ),
        migrations.AddField(
            model_name='img',
            name='your_file',
            field=models.FileField(blank=True, null=True, upload_to='your_directory/', verbose_name='Файл'),
        ),
    ]
